In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.datasets import load_diabetes

# tranin test

In [3]:
df = pd.read_csv("train (2).xls")

In [4]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
dff=df[["PassengerId","Pclass","Fare"]]

In [6]:
dff

     PassengerId  Pclass     Fare
0              1       3   7.2500
1              2       1  71.2833
2              3       3   7.9250
3              4       1  53.1000
4              5       3   8.0500
..           ...     ...      ...
886          887       2  13.0000
887          888       1  30.0000
888          889       3  23.4500
889          890       1  30.0000
890          891       3   7.7500

[891 rows x 3 columns]

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_train,X_test,y_train,y_test = train_test_split(dff[["PassengerId","Pclass"]],dff["Fare"],test_size=0.2,random_state=2)

In [9]:
X_train.sample(5)

     PassengerId  Pclass
381          382       3
804          805       3
607          608       1
119          120       3
248          249       1

In [10]:
X_train.isnull().sum()

PassengerId    0
Pclass         0
dtype: int64

In [11]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.impute import SimpleImputer

In [13]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
import pickle



# Numerical pipeline
num_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

# ColumnTransformer (only column names)
preprocessor = ColumnTransformer(
    transformers=[
        ('num', num_pipeline, ["PassengerId","Pclass"])
        
    ]
)
# Final pipeline
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', RandomForestRegressor(n_estimators=100, random_state=42))
])

# Features and Target
X = X_train
y = y_train

# Fit
pipeline.fit(X, y)

# Predict
#y_pred = pipeline.predict(X_test)

#print(y_pred)

pickle.dump(pipeline, open("model.pkl", "wb"))

print("Pipeline Saved!")

Pipeline Saved!